### ISSUE TITLE
Set up Google Analytics 

### ISSUE THREAD

**Issue by andrablaj** [medic/cht-tech-radar-contributors#1]
Set up Google Analytics for the CHT Technical Radar for Contributors so we can have insights on its usage by the community.

**Comment by garethbowen** [comment]
I suggest we use the same Google Analytics tracker as the docs site as I don't really see any advantage to creating a new one. The instructions to set this up are...

> Below is the Google tag for this account. Copy and paste it in the code of every page of your website, immediately after the <head> element. Don’t add more than one Google tag to each page. 

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-98W4V2NTPJ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-98W4V2NTPJ');
</script>
```

It looks like we can add arbitrary HTML following the instructions here: https://github.com/AOEpeople/aoe_technology_radar/tree/main#change-the-indexhtml

**Comment by andrablaj** [comment]
This is done via [medic/cht-tech-radar-core](https://github.com/medic/cht-tech-radar-core), which contains CHT style customizations and Google Analytics setup that both Tech Radars use. 

@garethbowen is there a way to check if Google Analytics considers this radar?

**Comment by garethbowen** [comment]
I can see `cht-tech-radar-contributors` listed in google analytics so it appears to be working.

You're also an administrator for the property so you can check by going to analytics.google.com and navigating to "CHT Doc Site GA4" > Reports > Engagement > Pages and screens.

**Comment by andrablaj** [comment]
Perfect, I just checked it myself too (I forgot I had the access rights).
