### ISSUE TITLE
tooltip graphic covers up bottom center part of tooltip text

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-tech-radar-contributors#36]
When you hover your mouse around on the radar to see the tooltips, the text of the tool tip is slightly obscured.  For text like `git` or `npm` this can make it illegible:

![image](https://github.com/medic/cht-tech-radar-contributors/assets/8253488/ba450ca2-4cc1-4310-8c5a-d7b243e42ca3)

Here's a movie of the same:

https://github.com/medic/cht-tech-radar-contributors/assets/8253488/4ccf59c0-33a3-4ea5-aff4-9615f6027f90

**Comment by andrablaj** [comment]
This will be closed by https://github.com/medic/cht-tech-radar-contributors/pull/27, which upgrades the Tech Radar to AOE's tech radar v4, where this issue is fixed.

**Comment by mrjones-plip** [comment]
yay - looks great - thanks Andra!

[Screencast from 09-27-2024 09:41:10 AM.webm](https://github.com/user-attachments/assets/b8534193-01c4-4966-bb73-12f16e659465)
